version: "3.9"

services:
  in-cse:
    image: ankraft/acme-onem2m-cse:latest
    container_name: in-cse
    ports:
      - "8080:8080"
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/webui >/dev/null || curl -fsS http://localhost:8080/ >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  gateway-app:
    build: .
    image: ${IMAGE}
    container_name: gateway-app
    depends_on:
      in-cse:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "9000:9000"
    environment:
      IN_CSE_BASE_URL: ${IN_CSE_BASE_URL}
      ORIGINATOR_ID: ${ORIGINATOR_ID}
      CALLBACK_URL: ${CALLBACK_URL}
      host_cse_base_dir:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      HOST_CSE_BASE_DIR: /Users/kimminseo/Documents/CMPSC483W/PSU_CAPSTONE_1S26/cse-data
      CONTAINER_CSE_BASE_DIR: /shared-cse

      # TLS_ENABLED: ${TLS_ENABLED:-false}
      # TLS_VERIFY: ${TLS_VERIFY:-true}
      # TLS_CA_CERT: ${TLS_CA_CERT:-/run/certs/ca.pem}
      # TLS_CLIENT_CERT: ${TLS_CLIENT_CERT:-/run/certs/client.crt}
      # TLS_CLIENT_KEY: ${TLS_CLIENT_KEY:-/run/certs/client.key}
      DOCKER_HOST: ${DOCKER_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/kimminseo/Documents/CMPSC483W/PSU_CAPSTONE_1S26/cse-data:/shared-cse
      
    restart: unless-stopped
    # networks: #only valid when everything is on one laptop
    #   - onem2m-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  onem2m-net:
    driver: bridge

  