; CSE type: IN
; Environment: Development
;

[basic.config]
cseType = IN
cseID = id-in
cseName = cse-in
serviceProviderID = //acme.example.com
adminID = CAdmin
networkInterface = 0.0.0.0
cseHost = acme-in
httpPort = 8080
cseSecret = MY_SECRET
databaseType = tinydb
logLevel = debug
consoleTheme = dark

[cse.registration]
allowedCSROriginators = /id-in,/id-mn1,/id-mn2
allowedAEOriginators = C*,S*,/id-in/C*

[textui]
startWithTUI = false

[cse.operation.requests]
enable = true

[http]
enableUpperTesterEndpoint = true
enableStructureEndpoint = true
enableManagementEndpoint = true

[logging]
enableScreenLogging = true

; [database]
; resetOnStartup = true

