@startuml
hide footbox

participant GA as "GatewayAgent"
participant MN as "MN-CSE (ACME)"
participant IN as "IN-CSE (ACME)"
participant CB as "Orchestrator Application"

note over GA,CB
run components on host machine in separate docker containers
end note


CB -> IN: CREATE <AE> as Corchestrator

GA -> IN: CREATE <AE> as Cgatewayagent
GA -> IN: CREATE subscription to Cgatewayagent/cmd
GA -> IN: CREATE Cgatewayagent/data (MN-CSE name)
GA -> IN: CREATE Cgatewayagent/cmd (execute)

...

note left CB
Orchestrator subscribes to <Cgatewayagent> resources : TBC
end note



note left CB
Orchestrator creates <container>
resource (and <contentInstance>) 
describing the Gateway(MN-CSE)
end note

CB -> IN: CREATE Cgatewayagent/data/<cin> (MN-CSE name)
CB -> IN: CREATE Cgatewayagent/cmd/<cin> (execute)

IN -> GA: NOTIFY of new Gateway resource Cgatewayagent/cmd
GA -> IN : Gateway Agent retrieves Cgatewayagent/cmd/<contentInstance>

note over GA
Checks the command == 'execute'
Deletes Cgatewayagent/cmd/<contentInstance>
end note

GA -> IN : Gateway Agent retrieves Cgatewayagent/data/<contentInstance> 

note over GA
modify config.ini with the 
mn-cse name and id 
(re)start MN-CSE in docker
end note

note over GA, MN
Gateway Agent registers with MN-CSE
(this is a second registration - 
use a different <AE> name) 
end note

GA -> MN: CREATE <AE> as GatewayAgentMN

=== steady state ===

note left CB
Orchestrator changes the MN-CSE configuration
creates <contentInstance> with new data (change port)
in Cgatewayagent/gateway/data resource
end note

CB -> IN: CREATE contentInstance in Cgatewayagent/gateway/data resource
note over MN,IN
IN-CSE notifies Gateway Agent of new data
end note
IN -> GA: NOTIFY of new data (new port)


note over GA
modify config.ini with the 
mn-cse name and id 
(re)start MN-CSE in docker
end note

@enduml
