[Interface]
PrivateKey = qLa8xHFqMc1l7L45/duTuNkzMNqielVwtve66sdFqUU=
Address = 10.0.0.2/24

[Peer]
PublicKey = apIg4ZQmAiOQ4m9Z3Ncn4zKU3ieCpIeApbp1214S6G0=
AllowedIPs = 10.0.0.0/24
Endpoint = 127.0.0.1:51820
PersistentKeepalive = 25
